### ISSUE TITLE
The box collides with local apache install running on port 80

### ISSUE THREAD

**Issue by zlee-nucleussec** [josephgagliardi/chaplin#1]
Running `vagrant share` doesn't work, so I have to specify a port with `vagrant share --http 80`, but this is what my local xampp install uses, so vagrant share is actually sharing my port 80 locally. Changing apache in the image to run on port 8080 doesn't take. TBF, I am not super familiar with non-RHEL/CentOS distros of linux, and it's weird to me to have to change the port to 8080 in 400 places. 

I would like an easy way to change what port Apache uses so I can forward my local XAMPP install to the port in apache runs in the image. Ideally, 8080, but it doesn't really matter.

**Comment by josephgagliardi** [comment]
External and widespread error with vagrant share native to newer versions of vagrant

Custom port fowarding is an option and can be added to the vagrantfile but for now recommendation is to downgrade to vagrant 1.8.5 as noted in commit [3e75eb52c](https://github.com/josephgagliardi/chaplin/commit/3e75eb52c920cee7b490e8bbdf8a4dc6a4245e37)
